# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d50e71689ff19e56fb8dc173af06e39ceef06b006f41f1c95d28135e05f76efa4c8b1bc9638e1a9966e265af9fe45d003358396335220285329464442675371

test:
  secret_key_base: ef63b063ac1316ae83b61f54653a69338c6e20ceada155ee358162e4a6360a4987cfbc8b98a8405c9f6807a6e09ca41438be9f876a63dc6acd12fbdaae2f72d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
